### ISSUE TITLE
Circular Import rosbag

### ISSUE THREAD

**Issue by saurabh1002** [PRBonn/kiss-icp#123]
https://github.com/PRBonn/kiss-icp/blame/52a99d034318241d354ab2a50c7924572de70314/python/kiss_icp/datasets/rosbag.py#LL31C24-L31C24

The file `rosbag.py` in python dataloader has an `import rosbag` which is conflicting with the actual rosbag library

**Comment by nachovizzo** [comment]
Thanks for pointing this out,

as far as I know, this is not a problem since Python3. In python one had to do: `from future import absolute_import`. But not anymore. It might be that your linter is not happy about it, but should work, and on my end is also working.

More info: https://peps.python.org/pep-0328/
