### ISSUE TITLE
Add  `find_external_dependency` cmake function

### ISSUE THREAD

**Issue by nachovizzo** [PRBonn/kiss-icp#130]
After the cleanup don in #129 it's even more clear that there must be a function that replace the repetead pattern found everywhere in the 3rdparty dependency folder.

It's even more clear for the header only libraries:

```cmake
option(USE_SYSTEM_EIGEN3 "Use system pre-installed Eigen" ON)
```

and then
```cmake
if(USE_SYSTEM_EIGEN3)
  find_package(Eigen3 QUIET NO_MODULE)
endif()
if(NOT USE_SYSTEM_EIGEN3 OR NOT TARGET Eigen3::Eigen)
  set(USE_SYSTEM_EIGEN3 OFF)
  include(${CMAKE_CURRENT_LIST_DIR}/eigen/eigen.cmake)
endif()
```

It's always the same, the only thing that changes is the name of the library and the target, for example for sophus:
```cmake
option(USE_SYSTEM_SOPHUS "Use system pre-installed Sophus" ON)
```

and then:
```cmake
if(USE_SYSTEM_SOPHUS)
  find_package(Sophus QUIET NO_MODULE)
endif()
if(NOT USE_SYSTEM_SOPHUS OR NOT TARGET Sophus::Sophus)
  set(USE_SYSTEM_SOPHUS OFF)
  include(${CMAKE_CURRENT_LIST_DIR}/sophus/sophus.cmake)
endif()
```

**Comment by YashGaur000** [comment]
I wanna work on this issue. Can we make a separate file in 3rd party folder with the name of "no_repetition" which will check the 3rd party folder if there's any repetition?

OR

Should I place the repetition searching function in every file?

Please guide me more on this issue as I am lil bit confusing what to do exactly? Also, why's 3rd party folder's file is in .txt format, in which language am i suppose to write function? in .txt format?

Please reply ASAP, I'm looking forward to your reply so that I can start working on this issue.

**Comment by nachovizzo** [comment]
@YashGaur000 I highly recommend first watching my lecture on build systems on [YouTube](https://www.youtube.com/watch?v=zOmUHM0sFOc). 

Without knowing cmake it is impossible to solve this task.
