### ISSUE TITLE
Failure case study

### ISSUE THREAD

**Issue by yanconglin** [PRBonn/kiss-icp#151]
Thank you for releasing the tool.
Recently I am tryin KISS_ICP on waymo for ego motion estimation. However, I find several failure case where the model goes substantially wrong. Attached please find an example. Could you please tell me how to fix this issue (e.g., picking the correct parameters)?

The figure shows two registered frames (colored in blue and green). As you can see the the non-ground points do not align. 
![Screenshot from 2023-05-01 10-18-10](https://user-images.githubusercontent.com/26435516/235427959-c381c8a6-ac24-420b-957e-cacd0cd64ecf.png)

**Comment by benemer** [comment]
Hey,

this is hard to say without having the data at hand. Can you specify which data you used?

Are these the first two frames of the sequence? Is the car already in motion?

**Comment by yanconglin** [comment]
yes, I have shared the source with you. 
Here is a mini example: [kiss_icp_waymo_failure](https://drive.google.com/drive/folders/1C_b1mIvIVKIXdxVcJiyCNLUEMyeSf0DT?usp=sharing)

**Comment by benemer** [comment]
Thank you!

I think I found the problem. When estimating the first relative pose, we do not have a good initial guess since our prediction model requires at least two estimated poses (assuming no other sensors like IMU or wheel odometry). Therefore, we initialize our estimation with an identity pose. KISS-ICP finds a local minimum by aligning the scan lines as you can see in your image. We found that KISS-ICP usually recovers from this after some frames (check for example KITTI odometry sequence 12). In your case, 5 frames is probably not enough. Have you tried running it on the whole sequence?

A fast way to improve this is to increase the `initial_threshold` parameter. If you for example set it to 10, you will 1. keep all correspondences and 2. reduce their suppression by the robust kernel. Using the default parameters and increasing the initial threshold to 10, the pipeline already recovers after a couple of frames:

https://user-images.githubusercontent.com/38326482/235620071-52cb452f-ebf3-4910-a861-44c10f72ca9f.mp4

However, these are rather edge cases for which you might need to find a more customized initialization phase or the integration of other sensors.

**Comment by yanconglin** [comment]
many thanks for the reply.  Strange, increasing "initial_threshold: 10.0" does not help on my local machine. 
Can you please share with me the config file.

**Comment by benemer** [comment]
Are you using our pipeline and visualizer? I did not use the code you sent me except the data loading part to convert the point clouds to `ply` files. I used [this](https://github.com/PRBonn/kiss-icp/blob/main/config/basic.yaml) config with only the `initial_threshold` parameter changed.

**Comment by yanconglin** [comment]
I am using class [KISS_ICP](https://github.com/PRBonn/kiss-icp/blob/1b0529169b2461272a97e959e2a9deea57dbb661/python/kiss_icp/kiss_icp.py#L34), with my own datalodaer which directly takes as input the given '.npz' file as indicated in the code snippet.

**Comment by benemer** [comment]
In the snippet you sent me you are importing `KissICP` but using the `egomotion` class instead.

**Comment by yanconglin** [comment]
well, I renamed "KISS_ICP" class to "egomotion" class  for the clarity (for the project I am working on).  The "egomotion" class is simply a copy of KISS_ICP" class. I do not want to alternate the KISS_ICP codebase. sorry for the confusion

**Comment by benemer** [comment]
Ah okay! I did not compare if it's exactly the same.

**Comment by benemer** [comment]
You are passing the wrong timestamps. This is supposed to be a `N x 1` numpy array of the individual timestamps for each of the `N` points in the frame.

**Comment by yanconglin** [comment]
Hi, again,  I would like to ask if KISS-ICP is deterministic, as I obtained slightly different results on the same sequence. I wonder if there is a way to fix the randomness or am I making a mistake? This would be great for debugging, since KISS-ICP is the very first step of a complicated framework.

**Comment by benemer** [comment]
What kind of randomness are you observing, so how much does it affect the results?

**Comment by yanconglin** [comment]
Hi, I am using KISS-ICP for ego-motion estimation. each time it outputs a slightly different result. Currently, I am debugging my model, which requires a deterministic pose from ego-motion estimation.

**Comment by benemer** [comment]
I moved this to a new issue since this is already closed, see https://github.com/PRBonn/kiss-icp/issues/165
