### ISSUE TITLE
Output result format

### ISSUE THREAD

**Issue by rlabs-oss** [PRBonn/kiss-icp#3]
Please give a hint as to the fields in the ..txt output file contained in the results folder when processing .xyz dataset.
Thank you.

**Comment by nachovizzo** [comment]
Hello @rlabs-oss sorry for not printing a more detailed output on the CLI interface. We use the kitti-format, since we think it is quite standard. If you want to visualize the trajectory, you could use the evo tools for example(`pip install evo) and run the following command to see the output:

```sh
evo_traj kitti results/latest/*.txt -p
```

As an example, after running sequence `07` of the KITTI dataset and plotting the results I obtained this:
![image](https://user-images.githubusercontent.com/21349875/193849306-7ded2fdc-5e12-446f-a74d-c180b49dda68.png)

**Comment by rlabs-oss** [comment]
Thank you - much appreciated.
