### ISSUE TITLE
kiss_icp_pipeline and lidar_visualizer error

### ISSUE THREAD

**Issue by kanhw** [PRBonn/kiss-icp#384]
when I use: kiss_icp_pipeline --dataloader kitti --sequence 00 --visualize dataset/
it shows:
![2024-08-06 10-08-28 的屏幕截图](https://github.com/user-attachments/assets/4324169e-1b86-4ccc-b092-a91f56f77bce)
The same to lidar_visualizer.Do you have any good solutions?

**Comment by nachovizzo** [comment]
Is not an error just a warning, we did fix it in lidar visualizer but won't fix for kiss icp as we have a new visualizer ready to deploy very soon https://github.com/PRBonn/kiss-icp/pull/379

In any case, this is because you have a newer version of open3d, if it relly bothers you you can downgrade `pip install open3d==0.17`

**Comment by kanhw** [comment]
Thank you for your reply, sorry to bother you again, I changed the version of open3d to 0.17, this warning will no longer appear, but the visualization will only show a single frame of the radar point cloud, the terminal displayes as shown in the figure.
![2024-08-06 16-13-28 的屏幕截图](https://github.com/user-attachments/assets/3e946ed9-f53a-4363-99b3-1120ee0161ce)
