### ISSUE TITLE
Could not find a version that satisfies the requirement kiss-icp

### ISSUE THREAD

**Issue by dallinbriggs** [PRBonn/kiss-icp#4]
When trying to install this in an Ubuntu bionic docker container with the command
```
pip install --user kiss-icp
```
I get the following output:
```
Collecting kiss-icp
  Could not find a version that satisfies the requirement kiss-icp (from versions: )
No matching distribution found for kiss-icp
```
This is with pip version `pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)`.

I was able to install it on another machine that had a newer version of pip. 

Is there a minimum version specified somewhere?

**Comment by nachovizzo** [comment]
Hello @dallinbriggs. You are using python 2, which has been deprecated since almost 3 years. Additionally, the pip version is ancient (`9.0.1`)

How can you fix this? With python is always a mess, but I'd try something along these lines:

1. `python3 -m pip install --user --upgrade pip`
2. Make sure your local site-packages binary path is part of your `$PATH`, in **my** system this is `export PATH=$PATH:$HOME/.local/bin/`
3. Then query for the `pip` version, should be twenty-something, in my case
```sh
$ pip --version
pip 22.2.2 from /home/ivizzo/.local/lib/python3.10/site-packages/pip (python 3.10)
```
or you can also try
```sh
$ pip3 --version
pip 22.2.2 from /home/ivizzo/.local/lib/python3.10/site-packages/pip (python 3.10)
```
4. Then `pip install -U kiss-icp` should get you the `kiss_icp_pipeline` CLI
