### ISSUE TITLE
Bad result on Maicity Dataset

### ISSUE THREAD

**Issue by Rotatingpencil** [PRBonn/kiss-icp#62]
Thanks for your excellent job！

But I cannot get a correct result on Maicity Dataset, here is the result:
![image](https://user-images.githubusercontent.com/62542727/218100615-16f2890b-e2a4-4bd5-b370-19f3e77a1228.png)

The x-axis of the first 10 frames stays invariant, which is incorrect. But the follow-up result is correct.
This Dataset runs well with [puma](https://github.com/PRBonn/puma), so I guess it's not the problem of the dataset.

What should I do to get a correct result?

**Comment by nachovizzo** [comment]
Hello there, we are aware of this error. 

Turns out that we couldn't imagine a real-world scenario where this actually occurs, so we are not providing a fix for this particular synthetic dataset, which already comes with GT poses.

If you want to try on synthetic data, I would actually recommend trying CARLA. Mai-city was not design to benchmark odometry systems.

If you have another opinion, please, feel free to comment on this.

Thanks!
