### ISSUE TITLE
Downsampling coefficients sizes

### ISSUE THREAD

**Issue by aniket-gupta1** [PRBonn/kiss-icp#65]
Hey, Good work with the paper and thanks for sharing your code. 

In the paper, you have mentioned that you use double downsampling using /alpha and /beta as coefficients. Can you tell what is the default value of these coefficients in the released code. 

Sorry, I could not find it anywhere.

**Comment by benemer** [comment]
Thanks!

You can find the values in Table 1 of our [paper](https://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/vizzo2023ral.pdf):

![image](https://user-images.githubusercontent.com/38326482/218386320-0536c945-1f40-48c5-a206-add86cdeae06.png)

In our code, we do not expose them as explicit parameters because we actually never change them. You can find them in the [Voxelize](https://github.com/PRBonn/kiss-icp/blob/main/src/cpp/kiss_icp/pipeline/KissICP.cpp#L75) method.
