### ISSUE TITLE
Changing voxel size using ROS2

### ISSUE THREAD

**Issue by rsc9421** [PRBonn/kiss-icp#96]
Why we cannot change the voxel size in https://github.com/PRBonn/kiss-icp/blob/main/ros/launch/odometry.launch.py#L51 ?.

 it is not the same as change the value in https://github.com/PRBonn/kiss-icp/blob/main/ros/ros2/OdometryServer.cpp#L54 ?

**Comment by nachovizzo** [comment]
I looked online and looks to be impossible to have a similar behavior as with ROS1. Basically defining the "argument" and only reading it if the user specify it, otherwise take it from the max range.

If you know how to do this, please! Open a pull request, we will be delighted to review and merge it
